import type { Metadata } from "next";
import { Bangers } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
	title: "Le Files",
	description: "Generated by create next app",
};

const banger = Bangers({
	weight: "400",
	subsets: ["latin"],
	display: "swap",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<script
				type="module"
				defer
				src="https://cdn.jsdelivr.net/npm/ldrs/dist/auto/spiral.js"></script>
			<body className={`${banger.className} antialiased`}>{children}</body>
		</html>
	);
}
